services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    ports:
      - "22222:22"
    networks:
      internal_net:
        ipv4_address: 192.168.1.100

  fake_switch_1:
    container_name: switch_1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.101

  fake_switch_2:
    container_name: switch_2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.102

  fake_switch_3:
    container_name: switch_3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.103

  fake_switch_4:
    container_name: switch_4
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.104

  fake_switch_5:
    container_name: switch_5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.105

  fake_switch_6:
    container_name: switch_6
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.106

  fake_switch_7:
    container_name: switch_7
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.107

  fake_switch_8:
    container_name: switch_8
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SWITCH_MODEL=syrotech_generic
    networks:
      internal_net:
        ipv4_address: 192.168.1.108

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
